application:
    appName: sgp

spring:
    application:
        name: sgpservice
    datasource:
        url: jdbc:mysql://localhost:3306/sgp?createDatabaseIfNotExist=true&usrSSL=false
        username: root
        password: root
    jackson:
        date-format: yyyy-MM-dd
        deserialization:
            fail-on-unknown-properties: false
    jpa:
        database: MYSQL
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    liquibase:
        change-log: classpath:/db/master.xml
        drop-first: true
server:
    port: 8080

app:
    TOKEN_ADMIN: pindaiba
    TOKEN_USER: abacate
